### ISSUE TITLE
BLUETOOTH NOT WORKING PROPERLY ACER E1-472g

### ISSUE THREAD

**Issue by Puarator** [Arrows21/Hackintosh-Acer-Aspire-E1-472G-54204G75Mnkk#1]
I installed mac OS catalina with the laptop same as your model Acer e1-472g but my problem is that the bluetooth cannot be switched off and it doesn't detect any bluetooth device.  I already booted to windows and boot back to mac os but still the same problem.  Any thoughts?

![image](https://user-images.githubusercontent.com/44149307/71661488-4505d100-2d89-11ea-98ab-c6b81af9e2ab.png)

**Comment by Arrows21** [comment]
You must pairing bluetooth device first in windows and next to pairing in hackintosh.

**Comment by Arrows21** [comment]
ou must pair the Bluetooth device first in Windows and next to pair in Hackintosh.

**Comment by Puarator** [comment]
> You must pair the Bluetooth device first in Windows and next to pair in Hackintosh.
Do you mean you always need to pair a new bluetooth device in windows first before pairing it in hackintosh or it's just going to be done one time? :<

**Comment by Arrows21** [comment]
![Screen Shot 2020-01-27 at 00 56 30](https://user-images.githubusercontent.com/13944787/73139380-1e913800-40a0-11ea-8952-c63d3cd900ee.png)
maybe the difference in the bluetooth card? maybe? or another possibility?
my leptop is fine and working.
